name: my_meltano_project
version: '1.0'
profile: meltano
config-version: 2
source-paths:
- transform/stage
- transform/mart
analysis-paths:
- transform/analysis
test-paths:
- transform/tests
data-paths:
- transform/data
macro-paths:
- transform/macros
snapshot-paths:
- transform/snapshots
target-path: .dbt
log-path: logs
modules-path: dbt_modules
clean-targets:
- .dbt
- dbt_modules
- logs
models:
  my_meltano_project:
    +materialized: "{{ env_var('DBT_MATERIALIZE_TABLES_AS', 'table') }}"
vars:
  # Update this line to use the larger datasets:
  rawdb_schema: TPCH_SF10
  rawdb_dbname: TRAINING_DB
