version: 2

sources:
  - name: raw
    database: TRAINING_DB
    schema: "{{ var('rawdb_schema') }}"
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier
