name: my_meltano_project
version: '1.0'
profile: meltano
config-version: 2
source-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
data-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: ../.meltano/transformers/dbt/target
log-path: logs
modules-path: dbt_modules
clean-targets:
- ../.meltano/transformers/dbt/target
- dbt_modules
- logs
models:
  my_meltano_project:
    +materialized: "{{ env_var('DBT_MATERIALIZE_TABLES_AS', 'view') }}"
vars:
  # Update this line to use the larger datasets:
  rawdb_schema: TPCH_SF100
