# This file is managed by the 'dbt' file bundle and updated automatically when `meltano upgrade` is run.
# To prevent any manual changes from being overwritten, remove the file bundle from `meltano.yml` or disable automatic updates:
#     meltano config --plugin-type=files dbt set _update transform/profile/profiles.yml false

config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      threads: 2
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE') }}"
      database: "{{ env_var('SF_DATABASE') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE') }}"
      schema: "{{ env_var('DBT_TARGET_SCHEMA') }}"
