# This is a basic workflow to help you get started with Actions

name: CI Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Installs Python 3.8
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Runs a single command using the runners shell
      - name: Install meltano
        run: pipx install meltano

      # Runs a single command using the runners shell
      - name: Install meltano project plugins
        run: meltano install

      # Runs a set of commands using the runners shell
      - name: Run the meltano pipeline
        run: |
          meltano elt tap-carbon-intensity target-jsonl
          echo "Extract-load completed successfully!"

      # Upload output files as CI artifacts
      # WARNING: do not use this option with sensitive data
      - name: Archive output files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sample-output-files
          path: |
            output
            !output/**/*.md
          retention-days: 2  # Remove artifacts after 2 days
